= Lab Exercise 3: Apache Ignite, embedded in Quarkus

== Why?

We have previously seen that it is quite simple to use the Java thin client to access Ignite. However, this connection mode has some limitations:

* Fewer technical possibilities:
** The Ignite services we want to call must already be deployed on the Ignite server nodes.
** The client cannot really receive events or provide additional services to the grid.
** The DataStreamer, which allows for fast data feeding, is not available in the Thin Client.
* It forces us to treat Ignite servers as off-the-shelf products. This complicates delivery and operation procedures in some complex structures.

An Ignite node can be configured in "client mode", meaning it will not host data (except for near cache) but can "contribute" its services to the grid.

In this TP, given the limited time available, we cannot explore all the possibilities of the framework. That's why we have chosen to introduce you to some aspects that, in our opinion, are useful in a microservice-oriented architecture with Quarkus.

== Presentation of the modules.

In TP3, we have 3 submodules:

* node-client: contains the Quarkus microservice code that will join the cluster in "client" mode.
* node-server: contains the Quarkus microservice code that will join the cluster in "server" mode.
** We will launch 2 instances of this microservice.
* node-service: a module that allows us to share common interfaces and models between "client" and "server."

In the client and server modules, the Boot and IgniteProducer classes are already ready to use. In addition to TP1 and TP2, besides the fact that we produce an 'Ignite' instance instead of 'IgniteClient', you will see some configuration differences:

[,java]
----
igniteConfiguration.setUserAttributes(Map.of("nodeType", "server"));
igniteConfiguration.setClassLoader(Thread.currentThread().getContextClassLoader());
igniteConfiguration.setPeerClassLoadingEnabled(true);
----

* We can assign attributes to nodes, which will be useful for selecting on which nodes we want to execute our actions (for example, we can imagine certain nodes dedicated to certain types of processing).
* It's better to specify the classloader.
* And finally, we enable remote class loading.

We need to add an *add-opens* for invoke in Java 11 (in the jar launch line, see the jvm.args property in the root pom.xml link:[here]):

----
add --add-opens java.base/java.lang.invoke=ALL-UNNAMED
----

On the client side, only one additional line indicates that we are starting in "client mode":

[,java]
----
igniteConfiguration.setClientMode(true);
----

First of all, let's compile the modules (if it's not already done):

[,shell]
----
./mvnw clean install
----

Now we can start our 3 microservices (in 3 different terminals, in IntelliJ, you can run the following commands directly from your IDE).

* On Mac/Linux

[,shell]
----
./mvnw -pl node-server quarkus:dev -Dnode.name=serverNode1
----

[,shell]
----
./mvnw -pl node-server quarkus:dev -Dnode.name=serverNode2 -Dquarkus.http.port=8082 -Ddebug=5007
----

[,shell]
----
./mvnw -pl node-client quarkus:dev -Dnode.name=clientNode1 -Dquarkus.http.port=8085 -Ddebug=5010
----

* On Windows

[,shell]
----
./mvnw -pl node-server quarkus:dev "-Dnode.name=serverNode1"
----

[,shell]
----
./mvnw -pl node-server quarkus:dev "-Dnode.name=serverNode2" "-Dquarkus.http.port=8082" "-Ddebug=5007"
----

[,shell]
----
./mvnw -pl node-client quarkus:dev "-Dnode.name=clientNode1" "-Dquarkus.http.port=8085" "-Ddebug=5010"
----

In the logs of one of the servers, you will see that the cluster consists of 2 servers and 1 client (not thin):

[,shell]
----
Metrics for the local node (to disable set 'metricsLogFrequency' to 0)
    ^-- Node [id=fc17aee8, uptime=03:10:09.579]
    ^-- Cluster [hosts=1, CPUs=12, servers=2, clients=1, topVer=19, minorTopVer=0]
----

The Swagger UIs are accessible here:

* (http://localhost:8080/q/dev-ui/io.quarkus.quarkus-smallrye-openapi/swagger-ui)
* (http://localhost:8082/q/dev-ui/io.quarkus.quarkus-smallrye-openapi/swagger-ui)
* (http://localhost:8085/q/dev-ui/io.quarkus.quarkus-smallrye-openapi/swagger-ui)

== Distributed Computing (https://ignite.apache.org/docs/latest/distributed-computing/distributed-computing)

This part of the API allows you to send code to execute on remote nodes. Very powerful, you can:

* Send code to execute on all nodes or according to a selection.
* Take advantage of load balancing and/or failover mechanisms.
* Decide the scheduling of sent tasks (FIFO, by priority, by load distribution).

The code in question is serialized so that it supports specific Ignite annotations (https://ignite.apache.org/docs/2.11.1/resources-injection#pre-defined-resources), even with Quarkus.

To call "Pure Quarkus" services, whose classes are "managed," we recommend using the following code in your IgniteClosure (or IgniteCallable or IgniteRunner):

[,java]
----
CDI.current().select(MyService.class).get().....
----

Also, be very careful with Anonymous classes, which, during serialization, carry the entire cluster of parent classes with them. This can sometimes cause issues during deserialization.

=== Sending code to all selected nodes.

____
CAUTION: The code sent to a remote node will be executed in an Apache Ignite thread. If you want to use a Quarkus service, it may be necessary to use the @ContextActivator annotation on it.
____

*Create a REST service in the node-client that injects an Ignite instance; we will use it.*

Let's say we want to execute a task on all server-type nodes, such as clearing caches, compressing directories, etc. The Ignite compute API allows us to send code to the chosen nodes.

To do this, we use the *IgniteCompute* class and its *broadcast()* method.

[,java]
----
@Slf4j
@Path("/ignite-tp3")
@RequiredArgsConstructor
@Produces(MediaType.TEXT_PLAIN)
public class ExerciceRest_3_3 {
    private final Ignite ignite;

    @GET
    @Path("/helloWorld/broadcastAll")
    public Response helloWorldBroadcastAll() {
        ignite.compute().broadcast(() -> LoggerFactory.getLogger("TESTREMOTE").info("===> Hello world !!"));
        return Response.ok().build();
    }
}
----

(the 'ignite' variable is injected by Quarkus; the instance is created by the Producer).

However, before the compute method addresses the entire cluster, including client-mode nodes, it can take a ClusterGroup as a parameter that selects the target nodes. To describe a ClusterGroup, simply use:

[,java]
----
ignite.cluster().forXXXX ....
----

____
Take the time to explore the various 'for...' methods; you will see that it is possible to finely select which nodes to act on.
____

For example, to select server nodes based on the attribute mentioned earlier:

[,java]
----
ignite.compute(
                ignite.cluster().forAttribute("nodeType", "server")
        ).broadcast(.....)
----

Alternatively, there is a direct (safer) method:

[,java]
----
ignite.compute(
                ignite.cluster().forServers()
        ).broadcast(.....
----

*Use the following code in a method of the REST service you created in node-client, then test it using the Swagger UI; you will see your message in the logs of all servers.*

[,java]
----
@GET
@Path("/helloWorld/broadcast")
public Response helloWorldBroadcast() {
    ignite.compute(
            ignite.cluster().forRemotes()
    ).broadcast(() -> LoggerFactory.getLogger("TESTREMOTE").info("===> Hello world !!"));
    return Response.ok().build();
}
----

*broadcast()* takes classes inheriting from IgniteRunnable, IgniteCallable, or IgniteClosure (Function) as parameters.

You have probably noticed that this code uses remote class loading.

*Replace 'broadcast' with 'run,' then press F5 on the client's Swagger UI (with Quarkus, this is enough to recompile/deploy your app), and you will see that when you call your REST service, only one node receives the message.*

By default, the broadcast method sends to all nodes that meet the cluster selection. The other methods perform load balancing. By executing your REST call several times, you will observe the distribution of log messages in the two server consoles.

By default, jobs are evenly distributed in RoundRobin fashion. However, it is possible to configure *JobStealing* to distribute the load on unoccupied nodes (https://ignite.apache.org/docs/latest/distributed-computing/load-balancing).

*Injected Resources*

To demonstrate the use of injected Ignite resources, create a class:

[,java]
----
public class GetNodeUID implements IgniteCallable<String> {
    @IgniteInstanceResource
    Ignite ignite;
    @Override
    public String call() throws Exception {
        return ignite.cluster().localNode().id().toString();
    }
}
----

Then, in a REST service, call and display the result:

[,java]
----
@GET
@Path("/getNodeUID")
public Response getNodeUID() {
    StringBuilder sb = new StringBuilder();
    ignite.compute(ignite.cluster().forServers())
        .broadcast(new GetNodeUID())
        .stream()
        .forEach(returned-> sb.append("Node UID = ").append(returned).append("\n"));
    return Response.ok(sb.toString()).build();
}
----

Out of curiosity, try using an anonymous class and observe the error produced when calling your REST service:

[,java]
----
@GET
@Path("/anonymousClass")
public Response anonymousClass() {
    ignite.compute(ignite.cluster().forServers())
            .broadcast(new IgniteCallable<String>() {
                           @IgniteInstanceResource
                           Ignite ignite;
                           @Override
                           public String call() throws Exception {
                               return ignite.cluster().localNode().id().toString();
                           }
                       }
            )
            .stream()
            .forEach(returned -> log.info("Captured = {}'", returned));
    return Response.ok().build();
}
----

*Calls can also be asynchronous*

And you can consume the response reactively! Add a REST method to test this:

[,java]
----
@GET
@Path("/async")
public Response async() {
    ignite.compute(ignite.cluster().forServers())
            .runAsync(() -> LoggerFactory.getLogger("listen").info("hello from client"))
            .listen(after -> log.info("return of listen"));
    return Response.ok().build();
}
----

The return code here is executed in a thread managed by Ignite. However, you can choose to use your own ExecutorService with the listenAsync method, allowing you to use a managed thread pool:

[,java]
----
@GET
@Path("listenAsyncManagedExecutor")
public void listenAsyncManagedExecutor() throws InterruptedException {
    log.info("Current Thread {}", Thread.currentThread());
    ignite.compute(ignite.cluster().forServers())
            .runAsync(() -> LoggerFactory.getLogger("listenAsyncManagedExecutor").info("hello from client"))
            .listenAsync(
                    after -> log.info("Return handled in thread {}", Thread.currentThread()),
                    managedExecutor
            );
    Thread.sleep(20000); // this guarantees that the current thread will not be used when the response comes
}
----

*Jobs can also be assigned by affinity key on a cache*

There are other job execution APIs, such as map/reduce (https://ignite.apache.org/docs/latest/distributed-computing/map-reduce). You can attempt an implementation of the example in Ignite's documentation (ComputeTaskExample).

== Ignite Services (https://ignite.apache.org/docs/latest/services/services)

It is also possible to deploy services on Ignite nodes and expose them using an interface.

Services can be deployed as:

* Singleton per Cluster
* Singleton per Node

But also:

* By affinity, by Node filter, etc.
* With a determined number of instances.

*In the node-service module, create an interface for your service.* For example:

[,java]
----
public interface MySimpleService {
    Integer add(Integer a, Integer b);
}
----

*In the node-server module,* add a Quarkus service implementing the interface (note the @Unremovable):

[,java]
----
@ApplicationScoped
@Slf4j
@RequiredArgsConstructor
@Unremovable
public class QuarkusIgniteService implements MySimpleService {
    @Override
    public Integer add(Integer a, Integer b) {
        log.info("Call add for {} and {}", a, b);
        return a + b;
    }
}
----

Then add the Ignite "service," which ultimately serves as a proxy:

[,java]
----
public class QuarkusIgniteServiceProxy implements Service, MySimpleService {
    private QuarkusIgniteService quarkusIgniteService;

    @Override
    public Integer add(Integer a, Integer b) {
        return quarkusIgniteService.add(a, b);
    }

    public void init() throws Exception {
        quarkusIgniteService = CDI.current().select(QuarkusIgniteService.class).get();
    }
}
----

All that's left is to add the service configuration in the Boot class of the server:

[,java]
----
ClusterGroup grp = ignite.cluster().forAttribute("nodeType", "server");
log.info("grp {}", grp.nodes());
ignite.services(grp).deploy(
        new ServiceConfiguration()
                .setName("MySimpleService")
                .setMaxPerNodeCount(1)
                .setService(new QuarkusIgniteServiceProxy())
);
----

Then, to test on the node-client side, create a REST service:

[,java]
----
@GET
@Path("/callRemoteAdd/{a}/{b}")
public void callRemoteAdd(@PathParam("a")int a, @PathParam("b")int b){
        MySimpleService mySimpleService = ignite.services(ignite.cluster().forAttribute("nodeType", "server"))
        .serviceProxy("MySimpleService", MySimpleService.class, false);
        log.info("Remote Call {} plus {} = {}", a, b, mySimpleService.add(a, b));

}
----

**Services, like jobs, can be deployed remotely, stopped, and redeployed.

== Other features.

If you still have time, explore the IgniteMessaging API, which is also very interesting in the context of a microservices application (https://ignite.apache.org/docs/latest/messaging)
