image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Java 17
    init: |
      sdk install java 17.0.8-oracle < /dev/null
      gp sync-done java

  - name: Generate and view PDF doc
    command: >
      gp sync-await java ;
      cd doc ;
      mvn ;
      gp open target/generated-docs/main.pdf

vscode:
    extensions:
        - vscjava.vscode-java-pack
        - redhat.java
        - asciidoctor.asciidoctor-vscode
        - anwar.papyrus-pdf
        - redhat.vscode-quarkus
        - vsls-contrib.codetour
