= Welcome to the Quarkus Ignite Lab

This repository contains the following elements:

* Lab documentation in the `doc` directory. To generate it, simply run the `mvnw` command in the doc directory from your terminal. The documentation will be generated in `target/generated-docs`.

TIP: The documentation is also available in the GitHub repository deliverables at: https://github.com/SCIAM-FR/quarkus-iginite-lab

*Materials for completing the lab in the form of:
Please refer to the documentation for more information about the lab.

## Opening the Workspace in Gitpod
To open the workspace, simply click on the *Open in Gitpod* button, or use https://gitpod.io/#https://github.com/SCIAM-FR/quarkus-iginite-lab.git.

image::https://gitpod.io/button/open-in-gitpod.svg[link=https://gitpod.io/#https://github.com/SCIAM-FR/quarkus-iginite-lab.git]

After opening the workspace in Gitpod, wait a few minutes, it's going to install the right version of Java (Java 17) and generate the docs with Maven. At the end, the main PDF file for the doc will automatically open in the workspace.

Big Thanks to Horacio https://github.com/LostInBrittany[@LostInBrittany] for his help with Gitpod!
